channels:
  - conda-forge
dependencies:
  - compilers
  - cmake
  - scikit-build
  - opencv
  - mesa-libgl-devel-cos7-x86_64 
  - mesa-dri-drivers-cos7-x86_64 
  - libxcb
  - glew
  - glfw
  - librealsense
