%YAML:1.2
body2world_pose: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  # data: [ 0, 1,  0, 0,
  #         0, 0, -1, 0,
  #        -1, 0,  0, 0.5,
  #         0, 0,  0, 1 ]
  data: [ 0, 1,  0, 0,
          0, 0, -1, 0,
         -1, 0,  0, 0.456,
          0, 0,  0, 1 ]
