name: Tests & Coverage

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python-version: [ "3.9" ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pym3t
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
      - name: Install pym3t
        run: |
          pip install .
      - name: Run tests
        run: |
          pip install pytest
          python -m pytest tests/
